// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiogdnrfobudedkwyclu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb2dkbnJmb2J1ZGVka3d5Y2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTg2MDQsImV4cCI6MjA3MDYzNDYwNH0.yo3Lf9sS0ZCrIqBrIvD-yfSWx-fGZbajYwEUCzuNqqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});